name: Strava to Calendar Sync

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual run'
        required: false
        default: 'Manual trigger'
  schedule:
    - cron: '30 1 * * *'  # runs every day at 1:30 AM UTC (11:30 AM Melbourne time)

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Create credentials directory
      run: mkdir -p credentials

    - name: Create Google credentials file
      run: echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials/token.json

    - name: Run sync script
      env:
        STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
        STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
        STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
        GOOGLE_CALENDAR_ID: ${{ secrets.GOOGLE_CALENDAR_ID }}
      run: python main.py
